# Generated by Django 3.2.4 on 2022-03-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment', '0004_customuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(default='Admin', max_length=30),
        ),
    ]
