# Generated by Django 3.2.4 on 2022-03-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jwt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.TextField()),
                ('refresh', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.CharField(max_length=50)),
                ('remita_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('TRANSFER', 'Transfer'), ('BANK DEPOSIT', 'Bank Deposit'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='TRANSFER', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField()),
                ('is_approved', models.BooleanField()),
                ('is_approved_all', models.BooleanField()),
            ],
        ),
    ]
