# Generated by Django 3.2.4 on 2022-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merge',
            name='payment_id',
            field=models.CharField(max_length=200),
        ),
    ]
