# Generated by Django 3.2.4 on 2022-02-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_repayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repayment',
            new_name='LoanRepayment',
        ),
    ]
