# Generated by Django 3.2.4 on 2022-02-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_rename_repayment_loanrepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='created_at',
            new_name='entry_date',
        ),
    ]
