# Generated by Django 3.2.4 on 2022-03-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_alter_merge_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
