# Generated by Django 3.2.4 on 2022-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_alter_loanrepayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='payment_method',
            field=models.CharField(choices=[('TRANSFER', 'Transfer'), ('BANK DEPOSIT', 'Bank Deposit'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='TRANSFER', max_length=30),
        ),
    ]
