# Generated by Django 3.2.4 on 2022-03-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_loanrepayment_is_flagged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='remita_id',
            new_name='remita_manadate',
        ),
    ]
