# Generated by Django 3.2.4 on 2022-03-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_rename_remita_id_loanrepayment_remita_manadate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='remita_manadate',
            new_name='remita_mandate',
        ),
    ]
