# Generated by Django 3.2.4 on 2022-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_loanrepayment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField()),
                ('is_approved', models.BooleanField()),
            ],
        ),
    ]
