# Generated by Django 3.2.4 on 2022-03-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_rename_remita_mandate_loanrepayment_remita_mandate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='is_mandate_closed',
            field=models.BooleanField(default=False),
        ),
    ]
