# Generated by Django 3.2.4 on 2022-02-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='merge',
            name='is_approved_all',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
