# Generated by Django 3.2.4 on 2022-03-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0011_alter_loanrepayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='payment_method',
            field=models.CharField(default='Transfer', max_length=100),
        ),
    ]
