# Generated by Django 3.2.4 on 2022-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0012_alter_loanrepayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
