# Generated by Django 3.2.4 on 2022-03-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0013_auto_20220318_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='repayment_posted',
            field=models.BooleanField(default=False),
        ),
    ]
